### ISSUE TITLE
Color of operators differ from color in default ruby-mode

### ISSUE THREAD

**Issue by yas375** [jacott/Enhanced-Ruby-Mode#11]
Hello!

At first: thank for this great mode! This mode solved for me problem with syntax highlighting inside `%{}` when there was different kind of quotes. See screens: [default ruby mode](http://content.screencast.com/users/yas375/folders/Jing/media/45caaece-7909-418a-b0e4-63a5007e79a8/00000268.png), [enhanced ruby mode](http://content.screencast.com/users/yas375/folders/Jing/media/13cd621c-08b6-4772-94e1-ed0e16e70ee5/00000272.png). And [here is our discussion about this](https://github.com/CocoaPods/CocoaPods/commit/8a314713b2cd3dea4cd597fb37b6528cd109ddb8#commitcomment-1126630).

But I have one more question: why color of operators (`<`, `+`, `=`) have changed? You could see changes on screens mentioned above.

Full my emacs config available here: https://github.com/yas375/emacs-config

Thanks in advance! =)

**Comment by jacott** [comment]
I'm glad you like the mode!

The operators are colored because I just wanted something more to highlight :)

Actually it is useful to have more hints in the emacs buffer so lisp code can easily detect operators. for example `$, |, ?, :, ->` are not always operators.  Currently I am not making any use of this.

If you don't like them being a different colour just customise the face `ruby-op-face` to the same as `default` face. See Also `customize-mode 'ruby-mode`

I hope that answers your question.

Cheers

Geoff

**Comment by yas375** [comment]
thank for your reply! =)
