### ISSUE TITLE
Problem with ruby-electric

### ISSUE THREAD

**Issue by Jell** [jacott/Enhanced-Ruby-Mode#8]
If I open an empty file and try to insert a new line with ruby-electric, I get

```
Debugger entered--Lisp error: (error "expression ends prematurely")
  signal(error ("expression ends prematurely"))
  error("expression ends prematurely")
  ruby-backward-sexp(1)
  ruby-electric-return-can-be-expanded-p()
  ruby-electric-return()
  call-interactively(ruby-electric-return nil nil)
```

If I type def followed by an empty space, I get a wrongly indented end:

``` ruby
# Input: def SPC
def 
  end
```

Also within a class body, every time I press enter a new end is added:

``` ruby
# Input: class RET RET RET
class



end
end
end
```

My guess is that the culprit is ruby-backward-sexp.

**Comment by Jell** [comment]
The first problem disappears if I change

``` elisp
(unless prop (error "expression ends prematurely"))
(goto-char pos)
```

to

``` elisp
(if pos
  (goto-char pos))
```

But I'm not sure of all the consequences of doing that...

**Comment by jacott** [comment]
What version of `ruby-electric.el` do you have?  I have 193 branch (svn r32501). This version does not have a `ruby-electric-return` function; hence I don't get the problems you are seeing.

The `def SPC` input treats the `end` as the method name. `def end` is not complete code and as such very much exception coding to cater for it. What about using `yasnippet` rather than turning on ruby-electric-mode?

I have updated the forward/backward sexp functions to not throw an error.

**Comment by Jell** [comment]
Thanks! I'll try the version you use.

**Comment by jacott** [comment]
Note: I'm also adding in syntax checking - which conflicts with flymake. It is faster and more precise as to where the error is but maybe a little bit buggy at the moment
